### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by thang-qt** [numToStr/site#1]
Saw this error when try to install : 
![ Log](https://i.imgur.com/5caKDu2.png)

**Comment by numToStr** [comment]
I found the source of this issue. I am using github api to showcase my projects. You have to set `GITHUB_TOKEN=<your_token>` in the environment variable. Make sure you have some pinned repository in your github account.

**Comment by thang-qt** [comment]
> I found the source of this issue. I am using github api to showcase my projects. You have to set `GITHUB_TOKEN=<your_token>` in the environment variable. Make sure you have some pinned repository in your github account.

Sure, i pinned 2 repo

**Comment by numToStr** [comment]
Does it work?

**Comment by thang-qt** [comment]
> Does it work?

No :(

**Comment by numToStr** [comment]
Never happened to me 🤔. For now you can remove the `src/pages/projects` file, if you want to run the app. 

I will have to investigate the issue.

**Comment by thang-qt** [comment]
> Never happened to me 🤔. For now you can remove the `src/pages/projects` file, if you want to run the app.
> 
> I will have to investigate the issue.

Can't fix it ?

**Comment by numToStr** [comment]
I saw your github. You don't have any pinned repository. Just pin one of them 🤞🙂.

**Comment by thang-qt** [comment]
Great, it's worked. Thank you so much =)
